# Create web hosts based on docker image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-charan
spec:
  selector:
    matchLabels:
      app: capstone-charan
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-charan
    spec:
      containers:
      - name: capstone-charan
        image: charankumarthirumala/charan.18
        imagePullPolicy: Always
        ports:
        - containerPort: 80